FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ./ .

RUN dotnet restore -f "./KedaScalingJob.ScaledJob/KedaScalingJob.ScaledJob.sln"  

WORKDIR "/src/KedaScalingJob.ScaledJob/"
RUN dotnet publish -c release -o /app --no-restore

# # final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "KedaScalingJob.ScaledJob.dll"]

# docker build -t dotknyl/keda-scaling-job:latest -f Dockerfile.scaling-job .      